### ISSUE TITLE
“Cannot detect browser version.” Pop-up in Wrapped Browser in iOS Application

### ISSUE THREAD

**Issue by saipal92** [KSEAWisconsin/kseawisconsin.github.io#39]
• Expected Behavior
No pop-up should be displayed when opening up the website.
• Actual Behavior
When opening up the website, “Cannot detect browser version.” pop-up shows up.
• Steps to reproduce
Open up the website in wrapped browser within iOS application (e.g. KakaoTalk).

**Comment by hyecheol123** [comment]
Looks like the wrapped browser does not send UserAgent, which used to include browser's type and version information, properly. Rather than relying on UserAgent parsing, I will fix the code to check specific functionality with the [method proposed by Mozilla Foundation](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Feature_detection).

Thanks for the bug report!!

**Comment by hyecheol123** [comment]
Resolved!!
